netInterfaceName: Ethernet
localDNSProxy: 127.0.0.1
nameservers:
  - 8.8.8.8:53
  - 8.8.4.4:53
blocklist:
  - ya.ru
  - mail.ru
localaliases:
  - my.beloded.io
blockAddress4: 0.0.0.0
blockAddress6: 0:0:0:0:0:0:0:0
configUpdate: true
updateInterval: 1m